name: Deploy dev

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: yarn install && cd _plugins && yarn install

    - name: Build
      run: yarn build

    - name: Deploy
      env:
        DEPLOY_HOST: ${{ secrets.DEV_SSH_HOST }}
        DEPLOY_KEY: ${{ secrets.DEV_SSH_KEY }}
        DEPLOY_KNOWN_HOSTS: ${{ secrets.DEV_SSH_KNOWN_HOSTS }}
      run: ./_scripts/deploy.sh _site
