name: Deploy
on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: actions/setup-node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn install
    - run: yarn build
    - run: yarn predeploy
    - run: yarn deploy
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        DEPLOY_KNOWN_HOSTS: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
        DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
